### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by ssbittle** [prenda-school/design-system#150]
### Variations:
**Types**: Info, Success, Warning, Error

**Design reference:**
[Figma file - Flag](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/Spark-Design-System-Web?node-id=2379%3A4207)

**Comment by WilliamKelley** [comment]
### Feedback
@ssbittle 
Similar to others, can you decide if Spark wants to prescribe a Transition for Flag? See all ready-made [Transitions here](https://material-ui.com/components/transitions/). See demos with our implementation parent component, Snackbar, [here](https://material-ui.com/components/snackbars/#transitions)

### Implementation
Implementation will be similar to SectionMessage and Banner, #151 and #149, styling Alert / AlertTitle.

Usage will also require knowledge and integration with [Snackbar](https://material-ui.com/components/snackbars). To that end, we should look into, validate, and story usage with the complementary project [notistack](https://material-ui.com/components/snackbars/#notistack).

There is no clear `variant` that is suited for Flag, which makes this component not suited for just overrides -- we should definitely export a custom wrapper of Alert. However, since the `"outlined"` variant is not used by SectionMessage or Banner, we can let Flag's stylings occupy that classes slot, and set `variant="outlined"` on our custom wrapper so the consumer never interacts with it and doesn't see the anachronism.

For a11y, there are very good links in the snackbar's page [section on a11y](https://material-ui.com/components/snackbars/#accessibility) which we need to investigate and account for in our prescriptions / examples for auto-hiding, hiding timeouts, resetting timeouts, stacking behavior and limits, roles, etc.

**Comment by ssbittle** [comment]
@WilliamKelley I like the transition of the snackbar. That makes most sense to me to incorporate for Flags.

**Comment by WilliamKelley** [comment]
@ssbittle Given the new elevations, I looked through to see if the Web components had been updated with such elevations.

Flag seems to be using one-off box-shadows. Is that intentional?

**Comment by ssbittle** [comment]
Updated> @ssbittle Given the new elevations, I looked through to see if the Web components had been updated with such elevations.
> 
> 
> 
> Flag seems to be using one-off box-shadows. Is that intentional?
