### ISSUE TITLE
Bad visual look from Unstable_Button baseline readjustments

### ISSUE THREAD

**Issue by alecdanz** [prenda-school/design-system#410]
Remove negative padding from the button component to make it even on all sides.

**Comment by alecdanz** [comment]
Sounds good I'll take a look at the release today to see if that resolves what I'm seeing.

**Comment by WilliamKelley** [comment]
You can look through all the stories on [our Chromatic hosted Storybook](https://60b7f55f55fbd4004993da4c-xvilqanggb.chromatic.com/?path=/story/ps-unstable-button--default) in the meantime. They should cover all the situations in which it can be rendered, including for with and without the v1 theme around it.

**Comment by alecdanz** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/48865151/170777547-6510af45-56b4-44b6-94a2-6ab23e82ec2f.png">

I'm still seeing that inside the Chromatic hosted storybook buttons. This is the padding I'm referring too.

**Comment by WilliamKelley** [comment]
That's margin, not padding, but understood. Again, that's intentional. Is it producing the wrong visual results? It's there purely to improve the visual results. Here's a before & after

**[before]**
![image](https://user-images.githubusercontent.com/25781782/170779477-305008b1-1208-44a3-a02d-a8d72bd8a448.png)
...
**[after]**
![image](https://user-images.githubusercontent.com/25781782/170779482-77d59504-d9ae-49a4-bb0d-2ce469c124ee.png)

**Comment by alecdanz** [comment]
Yes, take a look at this button from enrollments and you'll see what I mean. 

**Live**
<img width="248" alt="image" src="https://user-images.githubusercontent.com/48865151/170783251-4a9462a1-4316-4344-ae86-c232ab699cd1.png">

**Margin removed**
<img width="882" alt="image" src="https://user-images.githubusercontent.com/48865151/170783416-f2a5a4fe-32e3-49aa-9c99-397f9c953ed3.png">

**Comment by alecdanz** [comment]
All of our buttons look like they've partied a bit too hard right now haha

**Comment by WilliamKelley** [comment]
From what I can see in the repo, the latest enrollments deploy is using `1.0.0-alpha.6`, not `1.0.0-alpha.7`, so live examples there are moot.

**Comment by alecdanz** [comment]
But you didn't remove it between versions?

**Comment by alecdanz** [comment]
The button in Chromatic matches what I'm seeing in the live environment, I'm on safari as well, not sure if that would make things render differently between our machines.

**Comment by WilliamKelley** [comment]
That margin wasn't the problem, it was other stuff that conflicted with those values. Let's re-visit this once `alpha.7` is adopted.

**Comment by WilliamKelley** [comment]
Updated once more in `v1.0.0-alpha.8`

**Comment by WilliamKelley** [comment]
Okay, I figured that the issue is because browsers position the text differently when the line-height is not equal to the font size, **but** it's not a CSS controllable style. The only consistent fix is making font-size and line-height exactly the same (i.e. `line-height: 1`). Then vertical padding should be adjusted to make up for the size difference.
